### ISSUE TITLE
Solr cannot start because of corrupted downloaded file

### ISSUE THREAD

**Issue by linuxidefix** [BroadleafCommerce/DemoSite#1]
The file (solr-5.3.1.tgz) downloaded by the solr starter download at startup is always corrupted on linux.
- So decompressing file failed. If I download the file manually works perfectly.
- Seems to come from the download process: 
com.broadleafcommerce.admin.autoconfigure.SolrServer#downloadSolrIfApplicable

size: 137M md5 : c69eb24acb3821408eacf00651cc7022
instead of 
expected size: 129M md5 : c1eec12e2fabd38dfcd24c120295014

logs:
```
142853K of 142888K >>  2017-03-30 15:19:10.030  INFO 23778 --- [           main] c.b.admin.autoconfigure.SolrServer       : Expanding /tmp/solr-5.3.1/solr-5.3.1.tgz
gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
2017-03-30 15:19:10.175 ERROR 23778 --- [           main] c.b.admin.autoconfigure.SolrServer       : Unable to unpack /tmp/solr-5.3.1/solr-5.3.1.tgz. Make sure the running user has appropriate permissions to unpack the filein the same directory. Also, make sure the 'tar' command is available at the command prompt.

org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166) ~[commons-exec-1.3.jar:1.3]
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153) ~[commons-exec-1.3.jar:1.3]
	at com.broadleafcommerce.admin.autoconfigure.SolrServer.expandNix(SolrServer.java:337) [broadleaf-boot-starter-solr-5.2.0-SNAPSHOT.jar:na]
	at com.broadleafcommerce.admin.autoconfigure.SolrServer.expandDownload(SolrServer.java:277) [broadleaf-boot-starter-solr-5.2.0-SNAPSHOT.jar:na]
	at com.broadleafcommerce.admin.autoconfigure.SolrServer.downloadSolrIfApplicable(SolrServer.java:267) [broadleaf-boot-starter-solr-5.2.0-SNAPSHOT.jar:na]
	at com.broadleafcommerce.admin.autoconfigure.SolrServer.startSolr(SolrServer.java:119) [broadleaf-boot-starter-solr-5.2.0-SNAPSHOT.jar:na]
	at com.broadleafcommerce.admin.autoconfigure.SolrServer.start(SolrServer.java:82) [broadleaf-boot-starter-solr-5.2.0-SNAPSHOT.jar:na]
```

**Comment by cja769** [comment]
@linuxidefix Which linux distro are you using so that we can reproduce?

**Comment by linuxidefix** [comment]
@cja769 I am using linuxmint 18 64bits (it's like ubuntu ). I am using an oracle jdk 1.8.0_111
edit: I got it in class com.broadleafcommerce.admin.autoconfigure.SolrServer

downloadUrl is always "http://archive.apache.org/dist/lucene/solr/5.3.1/solr-5.3.1.zip" though  System.getProperty("os.name") ) = linux
String downloadUrl = String.format(props.getDownloadUrl(), props.getVersion(), props.getVersion());

the md5 matchs the zip version and I missed the log "Downloading Solr from http://archive.apache.org/dist/lucene/solr/5.3.1/solr-5.3.1.zip to /tmp/solr-5.3.1/solr-5.3.1.tgz"

**Comment by cja769** [comment]
@linuxidefix if you're not getting the "Downloading Solr from ..." log then that means the request to get the download file didn't return a 200. I'm not particularly sure why that would be though.

**Comment by linuxidefix** [comment]
@cja769 I get the downloading message. The bug is just props.getDownloadUrl() is always returning "http://archive.apache.org/dist/lucene/solr/%s/solr-%s.zip" with zip as default extension.

It should be something like http://archive.apache.org/dist/lucene/solr/%s/solr-%s.%s  in  com.broadleafcommerce.admin.autoconfigure.SolrProperties#downloadUrl

and in com.broadleafcommerce.admin.autoconfigure.SolrServer#downloadSolrIfApplicable
String downloadUrl = String.format(props.getDownloadUrl(),  props.getVersion(), props.getVersion(),(isWin?"zip":"tgz"));

**Comment by cja769** [comment]
@linuxidefix Ah sorry. I misunderstood your message before. After looking at the code more I'm not 100% sure how this works on OSX because you're right that it always downloads the `.zip` version and then tries to use `tar` to unpackage it. We have a dev working on a fix.

**Comment by phillipuniverse** [comment]
@linuxidefix we had some other things come up over the last few days. The issue with `SolrStarter` is resolved and pushed out to our nexus, let us know if you still have issues.
