### ISSUE TITLE
solr starting permission error in CentOS server

### ISSUE THREAD

**Issue by sharif2008** [BroadleafCommerce/DemoSite#38]
**c.b.solr.autoconfigure.SolrServer        : Problem starting Solr**

`java.io.IOException: Cannot run program "/tmp/solr-5.3.1/solr-5.3.1/bin/solr" (in directory "."): error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[na:1.8.0_171]
        at java.lang.Runtime.exec(Runtime.java:620) ~[na:1.8.0_171]
        at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61) ~[commons-exec-1.3.jar!/:1.3]
        at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279) ~[commons-exec-1.3.jar!/:1.3]
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336) ~[commons-exec-1.3.jar!/:1.3]
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166) ~[commons-exec-1.3.jar!/:1.3]
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153) ~[commons-exec-1.3.jar!/:1.3]
        at com.broadleafcommerce.solr.autoconfigure.SolrServer.startSolr(SolrServer.java:149) [broadleaf-boot-starter-solr-1.0.3-GA.jar!/:na]
        at com.broadleafcommerce.solr.autoconfigure.SolrServer.start(SolrServer.java:97) [broadleaf-boot-starter-solr-1.0.3-GA.jar!/:na]
`

**Comment by sharif2008** [comment]
I hadto re-mount the /tmp partition to run exec.
