### ISSUE TITLE
java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by zhu121972** [BroadleafCommerce/DemoSite#74]
try the DemoSite failed 
Waiting up to 30 to see Solr running on port 8983
2020-07-25 20:57:41.887 ERROR 1268 --- [           main] c.b.solr.autoconfigure.SolrServer        : Problem while checking core status: Connection refused: connect

java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_162]
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[na:1.8.0_162]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_162]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_162]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_162]
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_162]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_162]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_162]
        at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_162]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_162]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_162]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_162]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_162]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_162]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_162]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[na:1.8.0_162]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[na:1.8.0_162]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[na:1.8.0_162]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[na:1.8.0_162]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[na:1.8.0_162]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_162]
        at java.net.URL.openStream(URL.java:1045) ~[na:1.8.0_162]
        at com.broadleafcommerce.solr.autoconfigure.SolrServer.checkCoreStatus(SolrServer.java:191) [broadleaf-boot-starter-solr-2.2.1-GA.jar:na]
        at com.broadleafcommerce.solr.autoconfigure.SolrServer.startSolr(SolrServer.java:167) [broadleaf-boot-starter-solr-2.2.1-GA.jar:na]
        at com.broadleafcommerce.solr.autoconfigure.SolrServer.start(SolrServer.java:98) [broadleaf-boot-starter-solr-2.2.1-GA.jar:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) [spring-context-5.1.16.RELEASE.jar:5.1.16.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) [spring-context-5.1.16.RELEASE.jar:5.1.16.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) [spring-context-5.1.16.RELEASE.jar:5.1.16.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) [spring-context-5.1.16.RELEASE.jar:5.1.16.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) [spring-context-5.1.16.RELEASE.jar:5.1.16.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894) [spring-context-5.1.16.RELEASE.jar:5.1.16.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162) [spring-boot-2.1.15.RELEASE.jar:2.1.15.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) [spring-context-5.1.16.RELEASE.jar:5.1.16.RELEASE]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) [spring-boot-2.1.15.RELEASE.jar:2.1.15.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) [spring-boot-2.1.15.RELEASE.jar:2.1.15.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) [spring-boot-2.1.15.RELEASE.jar:2.1.15.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.1.15.RELEASE.jar:2.1.15.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.1.15.RELEASE.jar:2.1.15.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) [spring-boot-2.1.15.RELEASE.jar:2.1.15.RELEASE]
        at com.community.SiteApplication.main(SiteApplication.java:18) [classes/:na]

**Comment by cja769** [comment]
@zhu121972 First off, which OS are you using? 

After starting up and getting this error check port 8983 to see if Solr eventually started up. If it didn't then I would into the application logs to see where Solr was downloaded to, that is if you used SolrStarter to download it for you, and then manually start Solr manually (`./solr start` or `solr.cmd` depending on OS). Next start up the application again. If starting Solr manually fails then it sounds like the download was corrupted so I would delete the solr directory and start the application again so that it can redownload it.
